### ISSUE TITLE
sdl hangs

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3786]
**Reported by hboetes on 7 Apr 2013 15:22 UTC**
Upon exiting angband I sometimes get this hang if I press esc right after c-x

```
(gdb) bt
#0  0x00007f9d697bde75 in pthread_join () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f9d6be9161e in SDL_WaitThread () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#2  0x00007f9d6be8984a in SDL_AudioQuit () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#3  0x00007f9d6be88775 in SDL_QuitSubSystem () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#4  0x00007f9d6be887fe in SDL_Quit () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#5  0x000000000054a441 in hook_quit (str=0x0) at main-sdl.c:973
#6  0x0000000000542f5c in quit (str=0x0) at z-util.c:337
#7  0x0000000000544332 in main (argc=1, argv=0x7fff3772e3e8) at main.c:454
```

**Comment by angband-import** [comment]
**Comment by hboetes on 7 Apr 2013 15:32 UTC**
Another version of the same crash

```
Program terminated with signal 11, Segmentation fault.
#0  0x000000000053f18c in Term_gotoxy (x=0, y=23) at z-term.c:1481
1481		Term->scr->cx = x;
(gdb) bt
#0  0x000000000053f18c in Term_gotoxy (x=0, y=23) at z-term.c:1481
#1  0x000000000053f741 in Term_erase (x=0, y=23, n=255) at z-term.c:1732
#2  0x0000000000486f17 in handle_signal_abort (sig=11) at signals.c:200
#3  <signal handler called>
#4  0x000000000053f18c in Term_gotoxy (x=0, y=23) at z-term.c:1481
#5  0x000000000053f741 in Term_erase (x=0, y=23, n=255) at z-term.c:1732
#6  0x0000000000486f17 in handle_signal_abort (sig=15) at signals.c:200
#7  <signal handler called>
#8  0x00007f56f9b93e73 in pthread_join () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007f56fc26761e in SDL_WaitThread () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#10 0x00007f56fc25f84a in SDL_AudioQuit () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#11 0x00007f56fc25e775 in SDL_QuitSubSystem () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#12 0x00007f56fc25e7fe in SDL_Quit () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#13 0x0000000000548e25 in hook_quit (str=0x0) at main-sdl.c:973
#14 0x000000000054194c in quit (str=0x0) at z-util.c:337
#15 0x0000000000542d22 in main (argc=1, argv=0x7fff2665d588) at main.c:454
```

**Comment by angband-import** [comment]
**Comment by takkaria on 14 Apr 2013 18:02 UTC**
Possible dupe #1730

**Comment by angband-import** [comment]
**Modified by takkaria on 14 Apr 2013 18:02 UTC**

**Comment by angband-import** [comment]
**Comment by takkaria on 27 Apr 2013 23:17 UTC**
Assigning open bugs to 3.5 for fixing.

**Comment by angband-import** [comment]
**Modified by takkaria on 7 Dec 2013 17:06 UTC**

**Comment by angband-import** [comment]
**Comment by takkaria on 22 Dec 2013 13:49 UTC**
Can't reproduce this and it's after the game has already finished so not a high priority.  No longer a blocker.

**Comment by NickMcConnell** [comment]
Probably obsolete, closing.
