### ISSUE TITLE
Crash in SDL port upon exit

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3790]
**Reported by hboetes on 10 Apr 2013 17:59 UTC**
```
15:45  takkaria_| Han: probably won't be much crashing
15:45  takkaria_| if any
15:45  takkaria_| would be very surprised if there was crashing
15:51        Han| I can make anything crash ;-)
```

Heh :-)

```
warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/mega/home/han/src/Angband/angband.main/src/angband -msdl'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000053f2f4 in Term_gotoxy (x=0, y=23) at z-term.c:1481
1481		Term->scr->cx = x;
(gdb) bt
#0  0x000000000053f2f4 in Term_gotoxy (x=0, y=23) at z-term.c:1481
#1  0x000000000053f8a9 in Term_erase (x=0, y=23, n=255) at z-term.c:1732
#2  0x00000000004866e7 in handle_signal_abort (sig=11) at signals.c:200
#3  <signal handler called>
#4  0x000000000053f2f4 in Term_gotoxy (x=0, y=23) at z-term.c:1481
#5  0x000000000053f8a9 in Term_erase (x=0, y=23, n=255) at z-term.c:1732
#6  0x00000000004866e7 in handle_signal_abort (sig=15) at signals.c:200
#7  <signal handler called>
#8  0x00007f4f912cde73 in pthread_join () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007f4f939a161e in SDL_WaitThread () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#10 0x00007f4f9399984a in SDL_AudioQuit () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#11 0x00007f4f93998775 in SDL_QuitSubSystem () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#12 0x00007f4f939987fe in SDL_Quit () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#13 0x00000000005493cd in hook_quit (str=0x0) at main-sdl.c:973
#14 0x0000000000541ab4 in quit (str=0x0) at z-util.c:337
#15 0x00000000005432ca in main (argc=1, argv=0x7fffef205e38) at main.c:618
```

**Comment by angband-import** [comment]
**Comment by takkaria on 14 Apr 2013 17:58 UTC**
It's really helpful if you can give a description of what you were doing when the crashes happen!  Stack traces without context aren't so useful.

**Comment by angband-import** [comment]
**Comment by takkaria on 14 Apr 2013 18:01 UTC**
Also, is this not identical to #1726?

**Comment by angband-import** [comment]
**Comment by takkaria on 27 Apr 2013 23:17 UTC**
Assigning open bugs to 3.5 for fixing.

**Comment by angband-import** [comment]
**Comment by takkaria on 28 Nov 2013 11:34 UTC**
Duplicate of #1726
